# Generated by Django 5.0.7 on 2025-03-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='otp_expiry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
