# Generated by Django 5.0.7 on 2025-04-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
