# Generated by Django 5.0.7 on 2025-04-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otpcode_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='max_otp_try',
            field=models.IntegerField(default=3, max_length=2),
        ),
    ]
